### ISSUE TITLE
Maybe beta_f4 is defined twice with different priors in the horseshow code gpbf8rhs.stan line 89

### ISSUE THREAD

**Issue by zhengchencai** [avehtari/casestudies#2]
Hi Aki,

This case study is really nice, I mimicked the code to modify my GP model and it runs much faster and without divergence. The trick of normal_id_glm() played a big role in my case to speed up comparing to normal()

I am not sure if beta_f4 is defined twice with different priors in the horseshow code gpbf8rhs.stan. In line 89, it is using a normal prior that was used in the very first special day model gpbf8.stan with sigma_f4 ~ norm(0, 0.1) in line 103. But then in line 91, it is defined as the real horseshoe. Could you please check? 

  beta_f4 ~ normal(0, sigma_f4);
  // horseshoe
  beta_f4 ~ normal(0, sqrt( c_f4^2 * square(lambda_f4) ./ (c_f4^2 + tau_f4^2*square(lambda_f4)))*tau_f4);

**Comment by avehtari** [comment]
Oops, I hadn't noticed this issue (I'm involved in too many repos and github changed the way to see summary of issues :(
Yes, you are correct. This was fixed a couple weeks ago.
